### PR TITLE
Rtorr webpack build

### PR DESCRIPTION
**Pull request by rtorr**
Moved this to a pull request for ideas, feedback, and code review.

Its been literal years since I have worked with express, so there could maybe be a better way to handle things. I didn't have much time after work to implement this, so I know it's crude. Also, we could probably not serve the `packages` directory with express, and do that on the web server level (if there is one). 

So some notes:

- npm v2 is much easier to use because it will install peer dependencies.
- I am deleting the `packaged/node_modules` directory after every successful build.
- I could not find a way to dynamically create a node_modules path better than what is implemented, which added some constraints, and I assume some edge cases later on https://twitter.com/richardiii/status/667488434131374080. 
- no tests
- there could be potential problems when two or more users are creating a new package. this could be solved with dynamic node_module paths (check if package exists first, then build) and we could remove their node_modules to save space after the build. 
- Design
- is it ok that I brought in ejs? I am open to whatever people like.

To take a look. Load up my [branch](https://github.com/mjackson/npm-http-server/tree/rtorr-webpack-build), and go to `http://localhost:5000/package/immutable`.

### CODE REVIEW

**Comment by rtorr** [comment]
FYI: This pull request is not dead. I hope to work on this over the holiday break. Have some good ideas :tada:

**Comment by mjackson** [comment]
Awesome, thx for the update @rtorr! Looking forward to seeing your ideas around putting everything in a container :)

**Comment by rtorr** [comment]
Teaser update. I have made some progress.

Right now I have a docker container with with a web app. The idea would be to communicate with this server locally (or how ever you want). Its using 90% of `npm-http-server`'s code to look up packages and what not.

screen shot 2016-01-08 at 4 46 09 pm

**Comment by mjackson** [comment]
Awesome! So you're running `npm-http-server` inside a Docker container?

**Comment by rtorr** [comment]
@mjackson, 

Yes it's all running in a container. I am not running npm-http-server in a container, but the server that is running inside of the container makes use of some of the files in the modules directory. I figure if it ends up living in this project, I can import them for my code as well. A lot of the code for jsbundler does a lot of what you wrote as well (verifying with npm and versions). Hope to have it in a pull request this weekend. 

Any thoughts on how you want to communicate with this new service? npm-http-server could do a local request to the docker container, or you could have it on a different server altogether. Also, how do you want to store/copy over files from the container? You can set up a volume to /tmp on the container, for example.

**Comment by rtorr** [comment]
Curious if you would _like_ my code _and_ `npm-http-server` to be in the same docker container

**Comment by rtorr** [comment]
closed for https://github.com/mjackson/npm-http-server/pull/25

**Pull request closed without merging**
