### PR TITLE
Ignore node_modules and .eslintcache

### PR DESCRIPTION
**Pull request by nkbt**

### CODE REVIEW

**Comment by mjackson** [comment]
I put `node_modules` in my [global .gitignore](https://help.github.com/articles/ignoring-files/) so I don't have to ignore it on every project I work on.

**Comment by nkbt** [comment]
Me too, but that in not a common practice and usually it is good to have
one in gitignore. To make less choices I stick to the Github's .gitignore
for node ant top it up with some customizations if necessary.

**Comment by kentcdodds** [comment]
I find that making the local project `.gitignore` more explicit is helpful for newcomers :+1:

**Comment by mjackson** [comment]
Sure, I'll defer to you guys on this :+1:

**Pull request merged**
